language: java
jdk:
- oraclejdk8
script:
- mvn cobertura:cobertura
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: heroku
  api_key:
    secure: jBHYhU2Gx3ZXYTgicnATH2WevGaXlq/AVheTytJM0JgyaDMs1S9dt8/sbP4ICxhBqj7SWWF8GJXd+uGJxvTKUyvez4J1GTa0pgU+UC9ApBM8Nci5pdiBxcL9eGK8NtUqlnlLD4QH+uKzPW7uxQj6ap5quMTn97Z6HA03KF6Rq703B1UR46Hb5JKfmoQGwqtt68moj+xVdm6xyZDC7E1VnOHXSXw6ZuGNUZ6pxJUIY7p9nz/0IanBGxug5kALqi9XTB2c6RxG1WNl7frZU2XBuAK19WxtJ2BNCc7jFDImVOmDKVtKowL7CF+DIWtcr2Tb623W2qApkMALPz7uAIeObb/p9VlqHj6kJ1ZMQKIdzYSwF9RndYe4PR0J3tgikcH4Uba5KuPVdkrwcKSYbthye+0H98UGi5r7iUxS/BawVhNR//YJGWxMRfI1WKhIt+xtw4q3WVaNHapp2GL2sIHYgQAKL786YQgsuRf6SvDaP+oc+2jK7y42+jJs0mQ3W1zHemQpzD/jdkzPzS4US6LndNCqFAcyCCxgSQ9EVz+OiYtBmsdIsUZUYNzyYTPdaqFAR9/rw+jvqpyK2FtQifbpCaTRvy7TZxb03Oo1LOgpv8bPUMAHW4OY5+47xxpYYO5OdpQnXF47MdirfDiNysR3MUuMP1s7qWPTSONNmpyKloY=
  app: aplikasi-pengadaan
  on:
    repo: idtazkia/aplikasi-pengadaan
